[global]
strict init = true
buffer min = 1024
buffer max = 2MB
rotate lock file = /tmp/zlog.lock
default format = "%D.%us %-6V [%p][%f:%L] %m%n"
file perms = 600

[rules]
icg.* "/logfs/zte_icg_agg_log/icg.log",128M*3;